name: Deploy to prod

on:
  push:
    branches: ["main"]
    paths:
      - "rae-frontend/**"
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./rae-frontend"

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:ci

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages 🚀
        uses: Paahn/rae@main
